name: flutter_chatbot
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
  json: 0.20.4
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_secure_storage: ^6.0.0
  logging: ^1.0.0
  flutter_localizations:
    sdk: flutter
  clay_containers: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
